# Programix Settings

PROGRAMIX_THEME="light"
PROGRAMIX_LANGUAGE="en_US"
PROGRAMIX_TIMEZONE="Europe/Warsaw"
PROGRAMIX_NETWORK_MANAGER="NetworkManager"
PROGRAMIX_AUDIO_SYSTEM="PipeWire"
PROGRAMIX_POWER_PROFILE="balanced"
PROGRAMIX_AUTO_UPDATES="true"
