# Programix Settings

PROGRAMIX_THEME="dark"
PROGRAMIX_LANGUAGE="pl_PL"
PROGRAMIX_TIMEZONE="Europe/Warsaw"
PROGRAMIX_NETWORK_MANAGER="NetworkManager"
PROGRAMIX_AUDIO_SYSTEM="PipeWire"
PROGRAMIX_POWER_PROFILE="balanced"
PROGRAMIX_AUTO_UPDATES="true"
